### ISSUE TITLE
TGcollector Fails for Channels with Chinese Names: TypeError on ‘className’ in null

### ISSUE THREAD

**Issue by lujunjiehhh** [ahuseyn/TGcollector#4]
## Reproduction Steps:
- Added a channel with a Chinese name.
- After adding the task, the task failed to start, with the error “Telegram Scraper Fails for Channels with Chinese Names: TypeError on ‘className’ in null”.
## Attempted Solutions:
- Changed to an English-named channel, and the scraping worked normally.
- Modifying the task name did not resolve the issue.
![{68E1A138-315F-470a-A922-A9A5261C05DF}(1)(1)](https://github.com/ahuseyn/TGcollector/assets/49628289/a204f60b-6d88-4b31-8aaa-b7dede1a36fc)

**Comment by ahuseyn** [comment]
Hi,
Thank you for sharing this bug. Latest commit [8e87c7f](https://github.com/ahuseyn/TGcollector/commit/8e87c7f4830e7d614984e92307bf445910882a91) solved it.
