### ISSUE TITLE
Channel Collection Issue

### ISSUE THREAD

**Issue by gradstudentniu** [ahuseyn/TGcollector#7]
Hi There, 

One of the public channels I'm trying to collect on for my thesis using the TGcollector tool isn't recognized.  I get the following error: Channel could not be added: Error: Cannot find any entity corresponding to "https://t.me/+tqKDay0k5atmZWQ0"

I confirmed it is the correct link and added it to a folder to see if that would work as a work around but that did not work either. Any help would be appreciated. Thank you.

**Comment by ahuseyn** [comment]
Hi,
It seems to be a group. For now, TGC can only handle public channels.
